### ISSUE TITLE
Add a new linter

### ISSUE THREAD

**Issue by ciaranRoche** [aerogear/cordova-showcase-template#40]
## What
Currently, we use `tslint` in our `aerogear-js-sdk` whereas for our showcase app we are using the `ionic` lint script. See config file [here](https://github.com/aerogear/aerogear-js-sdk/blob/master/tslint.json)
## Why
We should follow the same conventions as our SDK in our showcase app.
## How
- Add tslint to showcase
- Add tslint check to circleci

**Comment by pawelpaszki** [comment]
@ciaranRoche I think this one can be closed now
